import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { LockKeyhole, MailCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Logo } from "@/components/site/Logo";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
const description="Acesso protegido à gestão da PromoraShop.";
export const Route=createFileRoute("/auth")({head:()=>({meta:[{title:"Acesso administrativo — PromoraShop"},{name:"description",content:description},{property:"og:title",content:"Acesso administrativo — PromoraShop"},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"},{name:"robots",content:"noindex, nofollow"}]}),component:Page});
function Page(){const navigate=useNavigate();const[loading,setLoading]=useState(false);const[firstAccess,setFirstAccess]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);const d=new FormData(e.currentTarget);const email=String(d.get("email"));const password=String(d.get("password"));if(firstAccess){const{error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/auth`}});setLoading(false);if(error){toast.error("Não foi possível iniciar o primeiro acesso.");return}toast.success("Enviamos um link de confirmação ao e-mail administrativo.");return}const{error}=await supabase.auth.signInWithPassword({email,password});setLoading(false);if(error){toast.error("Não foi possível entrar. Verifique seus dados.");return}await navigate({to:"/admin"})}return <main className="grid min-h-screen place-items-center bg-soft-gradient px-4 py-8"><div className="w-full max-w-md rounded-xl border border-border bg-card p-8 shadow-card"><Logo/><div className="mt-8 flex size-11 items-center justify-center rounded-lg bg-secondary text-primary">{firstAccess?<MailCheck/>:<LockKeyhole/>}</div><h1 className="mt-4 font-display text-2xl font-bold">{firstAccess?"Primeiro acesso":"Acesso administrativo"}</h1><p className="mt-2 text-sm text-muted-foreground">{firstAccess?"Crie sua senha e confirme sua identidade pelo e-mail autorizado.":"Área exclusiva da proprietária da PromoraShop."}</p><form onSubmit={submit} className="mt-8 space-y-5"><div className="space-y-2"><Label htmlFor="email">E-mail</Label><Input id="email" name="email" type="email" autoComplete="email" defaultValue={firstAccess?"arianearagaocomercial@gmail.com":""} readOnly={firstAccess} required/></div><div className="space-y-2"><Label htmlFor="password">Senha</Label><Input id="password" name="password" type="password" minLength={8} autoComplete={firstAccess?"new-password":"current-password"} required/></div><Button className="w-full" size="lg" disabled={loading}>{loading?"Aguarde…":firstAccess?"Criar acesso e confirmar e-mail":"Entrar com segurança"}</Button>{firstAccess?null:<Link to="/recuperar-senha" className="block text-center text-sm text-primary hover:underline">Esqueci minha senha</Link>}<Button type="button" variant="ghost" className="w-full" onClick={()=>setFirstAccess(value=>!value)}>{firstAccess?"Já tenho acesso":"Configurar primeiro acesso"}</Button></form></div></main>}