import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { LockKeyhole } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Logo } from "@/components/site/Logo";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/auth")({head:()=>({meta:[{title:"Acesso administrativo — PromoVip"},{name:"robots",content:"noindex, nofollow"}]}),component:Page});function Page(){const navigate=useNavigate();const[loading,setLoading]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);const d=new FormData(e.currentTarget);const{error}=await supabase.auth.signInWithPassword({email:String(d.get("email")),password:String(d.get("password"))});setLoading(false);if(error){toast.error("Não foi possível entrar. Verifique seus dados.");return;}await navigate({to:"/admin"})}return <main className="grid min-h-screen place-items-center bg-soft-gradient px-4"><div className="w-full max-w-md rounded-xl border border-border bg-card p-8 shadow-card"><Logo/><div className="mt-8 flex size-11 items-center justify-center rounded-lg bg-secondary text-primary"><LockKeyhole/></div><h1 className="mt-4 font-display text-2xl font-bold">Acesso administrativo</h1><p className="mt-2 text-sm text-muted-foreground">Área exclusiva da proprietária da PromoVip.</p><form onSubmit={submit} className="mt-8 space-y-5"><div className="space-y-2"><Label htmlFor="email">E-mail</Label><Input id="email" name="email" type="email" required/></div><div className="space-y-2"><Label htmlFor="password">Senha</Label><Input id="password" name="password" type="password" required/></div><Button className="w-full" size="lg" disabled={loading}>{loading?"Entrando…":"Entrar com segurança"}</Button></form></div></main>}